apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name | dump }}
  annotations:
    github.com/project-slug: rafaelsulimann/spring-backstage-test
spec:
  type: test
  owner: user:guest
  lifecycle: experimental
