name: 'Deploy'
description: 'Deploy application'
inputs:
  app_version:
    description: 'Application version'
    required: true
runs:
  using: "composite"
  steps:

    - run: |
        cd app/deployment/k8s/${{ values.name }}
        helm upgrade --install ${{ values.name }} ./ \
        --namespace ${{ values.orgName }} --create-namespace \
        --set=image.repository=ghcr.io/sulimanns/${{ values.name }} \
        --set=service.port=${{ values.applicationPort }} \
        --set=image.tag=${{ '${{' }} inputs.app_version}}
        
      shell: bash