apiVersion: v1
kind: Service
metadata:
  name: {{ include "${{ values.name }}.fullname" . }}
  labels:
    {{- include "${{ values.name }}.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "${{ values.name }}.selectorLabels" . | nindent 4 }}
